### ISSUE TITLE
Support dev mode with HTTPS

### ISSUE THREAD

**Issue by rvansa** [quarkiverse/quarkus-quinoa#99] opened 2022-06-13 14:19 UTC
Quinoa should check on `quarkus.http.insecure-requests` and when it's `disabled` it should go straight to the SSL port, when it's `redirect` it should follow the redirects. Right now it does not appear to be working.

**Comment by ia3andy** [comment] 2022-06-14 15:08
@rvansa have u tried something like this: 
https://create-react-app.dev/docs/using-https-in-development/

**Comment by rvansa** [comment] 2022-06-15 11:15
I was using this before moving over to Quinoa. Now I expect to get all the goodies for free, automatically :) (so not running `npm` manually).

**Comment by ia3andy** [comment] 2022-06-16 07:58
I've just tried ssl and it seems to work fine:
```properties
quarkus.http.ssl.certificate.file=cert.pem
quarkus.http.ssl.certificate.key-file=key.pem

quarkus.http.insecure-requests=redirect
```

I didn't manage to make the websocket work for HMR in proxy dev-mode using Vite. Everything else seems to work fine.

**Comment by ia3andy** [comment] 2022-06-16 08:00
FYI I am using RESTEasy Reactive, maybe the problem is with Classic + undertow?

**Comment by rvansa** [comment] 2022-06-16 08:10
Could be, we should really jump on reactive.

**Comment by melloware** [comment] 2023-03-23 23:10
@ia3andy now that we have solved HMR support can this ticket be closed?

**Comment by ia3andy** [comment] 2023-03-24 08:24
We can close this issue.

Something we don't yet have though is ssl support for the node dev server, but I guess having Quarkus with SSL make this kind of useless.

**Closed by ia3andy** 2023-03-24 08:24 UTC
