### ISSUE TITLE
Qwik framework support

### ISSUE THREAD

**Issue by ylemoigne** [quarkiverse/quarkus-quinoa#573] opened 2023-11-26 16:54 UTC
### Describe the bug

When using Qwik : https://qwik.builder.io/
Project created in webui with `npm create qwik@latest`

Starting quarkus.
The frontend is correctly started, If i go to `http://localhost:5173/demo/flower/` it works.
If I go to `http://localhost:8080/demo/flower/` i have a 404.

### Quinoa version

2.2.1

### Quarkus version

3.5.3

### Build / Runtime

Vite

### Package Manager

NPM

### Steps to reproduce the behavior

Using configuration
```
quarkus.quinoa=true
quarkus.quinoa.index-page=/
quarkus.quinoa.build-dir=dist/
quarkus.quinoa.dev-server.port=5173
quarkus.quinoa.enable-spa-routing=false
quarkus.quinoa.framework.detection=false
quarkus.quinoa.package-manager-command.dev=run dev
```

The frontend is correctly started, If i go to `http://localhost:5173/demo/flower/` it works.
If I go to `http://localhost:8080/demo/flower/` i have a 404.

I have edited `src/main/webui/package.json` ; in the script part to add debug to vite (`"dev": "vite --debug --mode ssr"`)
I can see that quinoa forward a request to same path to the dev server.

After some test, this `curl -X GET --location "http://localhost:5173/demo/flower/"` will return a 404.
But `curl -X GET --location "http://localhost:5173/demo/flower/"
    -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"` is 200 OK.

However `curl -X GET --location "http://localhost:8080/demo/flower/"
    -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"` reply with a 404.

So I suspect that quinoa doesn't forward the request with the right/original headers.

### Expected behavior

Going to `http://localhost:8080/demo/flower/` in the browser should produce the same result that going to `http://localhost:5173/demo/flower/`

**Comment by melloware** [comment] 2023-11-27 13:21
I am not positive but I think its similar to Svelte: https://github.com/quarkiverse/quarkus-quinoa/issues/547

The issue is this an SSR framework that does not support an `index.html` that Quinoa needs and it does its own serving and routing.

**Comment by ia3andy** [comment] 2023-11-27 13:30
Quinoa can't deal with frameworks not configured with static generation.

This is what you need to investigate: https://qwik.builder.io/docs/deployments/static/

**Comment by melloware** [comment] 2023-12-02 13:56
@ylemoigne will mark as WontFix but if you get it working please let us know so we can update the documentation similar to SvelteKit letting people know how they can get Qwik working.

**Closed by melloware** 2023-12-02 13:56 UTC
Labels: wontfix

**Comment by ylemoigne** [comment] 2023-12-05 11:20
Sorry for not answering sooner. 
The static generation is crashing so I was not able to make it work with Quinoa.

I did not have good understanding of both Qwik way, and Quinoa way of working when I've created the ticket, but it's ok as a won't fix.

Thanks for your answer and your work.
